### ISSUE TITLE
When we Call ConnectAPIHelper class through Batch Job throwing an exception as it is taking more than 150 DML Statements

### ISSUE THREAD

**Issue by Mohammedvazeer** [forcedotcom/ConnectApiHelper#13]
When we try to call the postFeedItemWithMentions method from Batch, everytime it is considering as one DML Statement, When the loop reach to 150th time, it is throwing an Exception "First error: Too many DML statements: 151". Is there any possiblity to avoid this issue like instead o calling everytime, can we add it in a list and call only once. Thanks in Advance...!!

**Comment by walahmad** [comment]
You should use ConnectApi.BatchInput (https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/connectapi_examples_post_feed_element_batch.htm) to make posts in batches as every write operation in ConnectApi costs one DML statement. 

You can still use ConnectApiHelper by calling getMessageSegmentInputs method and assigning your chatter post string to body.messageSegments list. See example below:
```apex
List<ConnectApi.BatchInput> batchInputs = new List<ConnectApi.BatchInput>();
for (Account thisAccount : targetAccountList) {
  ConnectApi.FeedItemInput input = new ConnectApi.FeedItemInput();
  input.subjectId = thisAccount.Id;
  ConnectApi.MessageBodyInput body = new ConnectApi.MessageBodyInput();
  body.messageSegments = new List<ConnectApi.MessageSegmentInput>(ConnectApiHelper.getMessageSegmentInputs(**'Hey there {005D00000015tjz}, how are you?'**));
  input.body = body;
  ConnectApi.BatchInput batchInput = new ConnectApi.BatchInput(input);
  batchInputs.add(batchInput);
}
ConnectApi.ChatterFeeds.postFeedElementBatch(Network.getNetworkId(), batchInputs);
```

**Comment by alouie-sfdc** [comment]
That's an excellent answer, thanks. I'm gong to close this issue.
