### ISSUE TITLE
Is there a way to support code snippet?

### ISSUE THREAD

**Issue by raghavkhaitan** [forcedotcom/ConnectApiHelper#14]
I also wanted to see if there is a way to Code Markup Type in this helper class?

**Comment by alouie-sfdc** [comment]
I haven't tested this, but I think the way to add support for code snippets is to add the entry

```
'code' => ConnectApi.MarkupType.Code
```

to the `supportedMarkup` map: https://github.com/forcedotcom/ConnectApiHelper/blob/master/force-app/main/default/classes/ConnectApiHelper.cls#L50-L58

That would allow you to write code snippets like `'<code>foo=bar</code>'` and then use the helper methods to post them.

**Comment by alouie-sfdc** [comment]
I ended up making the change and testing it. Please see https://github.com/forcedotcom/ConnectApiHelper/pull/24.
