### ISSUE TITLE
Does ConnectApiHelper work with the ConnectApi.EntityLinkSegmentInput subclass?

### ISSUE THREAD

**Issue by kbuckles-sfdc** [forcedotcom/ConnectApiHelper#19]
Does ConnectApiHelper work with the ConnectApi.EntityLinkSegmentInput subclass?

**Comment by douglascayers** [comment]
Potentially per https://github.com/forcedotcom/ConnectApiHelper/pull/15

**Comment by alouie-sfdc** [comment]
@kbuckles-sfdc, yes, I've finally merged the PR that @douglascayers referenced. Entity Links (links to records) are supported in ConnectApiHelper now, and the README has an example in https://github.com/forcedotcom/ConnectApiHelper#streamlined-rich-text-inline-images-and-record-links.
