### ISSUE TITLE
Change in postFeedElement v36

### ISSUE THREAD

**Issue by gjvilla** [forcedotcom/ConnectApiHelper#4]
Line 109 should be changed to 

return ConnectApi.ChatterFeeds.postFeedElement(communityId, input);

**Comment by alouie-sfdc** [comment]
Thanks for reporting this! The signature changed because v36.0 no longer gives you the option to attach a new binary file when posting a feed item (if you want to attach a file, it has to be one that already exists in Salesforce).

**Comment by JAertgeerts** [comment]
@alouie-sfdc Added PR with these changes..

**Comment by alouie-sfdc** [comment]
Closing this thanks to @JAertgeerts.
