### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mmetzinger** [forcedotcom/ConnectApiHelper#5]
I am getting the following error when trying to use the example post. 

Illegal assignment from ConnectApi.FeedElement to ConnectApi.FeedItem

Code:
ConnectApi.FeedItem fi = ConnectApiHelper.postFeedItemWithMentions(Network.getNetworkId(), 'me', 'Hey there {005D00000015tjz}, how are you?');

My class and the helper class are on V36 and I have made the correction to the one line of the helper method for the V36 change that is listed in this issues area.

**Comment by alouie-sfdc** [comment]
I think the readme needs to be updated. Does it work if you cast the FeedElement to be a FeedItem? For example:

```
ConnectApi.FeedItem fi = (ConnectApi.FeedItem) ConnectApiHelper.postFeedItemWithMentions(Network.getNetworkId(), 'me', 'Hey there {005D00000015tjz}, how are you?');
````

**Comment by mmetzinger** [comment]
That worked.

How can I set the RelatedRecordId for the same post? I need to associate
the post to a WorkThanks record. Easy enough to do normally. Just not sure
how to do with this helper method.

**Comment by alouie-sfdc** [comment]
Not sure about that. Work Thanks posts aren't supported in the ConnectApi family of methods, so you'll need to use the FeedItem sObject. Maybe you can do it like this after the above call to `ConnectApiHelper.postFeedItemWithMentions()`?
```
FeedItem f = new FeedItem(id = fi.id);
f.RelatedRecordId = 'your_record_id';
update f;
```

**Comment by mmetzinger** [comment]
That didn't work. However it got me thinking. How about I create my post as
normal and then have the helper method update it with the @mentions. I see
in the helper towards the bottom there are some other methods but i don't
know how to use them.  Can someone help me out?

This is how I create the FeedItem with the associated Work Thanks record.

                  //Post to Chatter
                  FeedItem F = new FeedItem(
                      Body = msg2,
                      CreatedById = cUser.Id,
                      ParentId = cGroup.Id,
                      RelatedRecordId = t.Id,
                      Type = 'RypplePost'
                  );
                  try {
                      insert F;
                  } catch(DmlException e) {
                      System.debug('The following exception has occurred: '
+ e.getMessage());
                  }

                  //Update Record with @Mention
                  //Here is where the connectapi should be called but don't
know how to do it.
