### ISSUE TITLE
Use Variable on the Post

### ISSUE THREAD

**Issue by cesaracb** [forcedotcom/ConnectApiHelper#8]
Hi! First of all thanks to post this to the community.

I have a doubt, not really a issue. 

I want to know if I there is a way that I can use a variable inside the String that will pass to the postFeedItemWithRichText method. 

Some like this:

 ConnectApi.FeedItem fi = (ConnectApi.FeedItem) ConnectApiHelper.postFeedItemWithRichText (Network.getNetworkId(), 'me', 'Hey there {005D00000015tjz}, **{some variable}** ?');

Then I could change the post based on some previous criteria.

But nevertheless thanks again for the code!

**Comment by alouie-sfdc** [comment]
Hi @cesaracb. Using other variables isn't supported, but if you wanted to, you could fork the code and implement your own variable parsing. I'm going to close this issue, but please feel free to re-open it if you have any more questions. Thanks.
